# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version '2.100.0'

lane :beforeRelease do

    ensure_git_branch(
        branch: '(release/*|hotfix/*)'
    )

    ensure_git_status_clean

    # ===

    pod_lib_lint(
        allow_warnings: true,
        quick: true
    )

    # === Remember current version number

    versionNumber = version_get_podspec(
        path: 'XCEPipeline.podspec'
    )

    puts 'Current VERSION number: ' + versionNumber

    # === Infer new version number

    newVersionNumber = git_branch.split('/').last

    puts 'New VERSION number: ' + newVersionNumber

    # ===

    version_bump_podspec(
        path: 'XCEPipeline.podspec',
        version_number: newVersionNumber
    )

    git_commit(
        path: 'XCEPipeline.podspec',
        message: 'Version Bump to ' + newVersionNumber + ' in Podspec file'
    )

end # lane :beforeRelease

lane :generateProjectViaCP do

    # === Regenerate project

    # default initial location for any command
    # is inside 'Fastlane' folder

    sh 'cd ./.. && pod gen --gen-directory="Xcode"'

end # lane :generateProjectViaCP

lane :generateProjectViaIce do

    # === Regenerate project

    # default initial location for any command
    # is inside 'Fastlane' folder

    sh 'cd ./.. && ice xc'

end # lane :generateProjectViaIce