# Customise this file, documentation can be found here:
# https://github.com/KrauseFx/fastlane/tree/master/docs
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# More information about multiple platforms in fastlane: https://github.com/KrauseFx/fastlane/blob/master/docs/Platforms.md
# All available actions: https://github.com/KrauseFx/fastlane/blob/master/docs/Actions.md

# By default, fastlane will send which actions are used
# No personal data is shared, more information on https://github.com/fastlane/enhancer
# Uncomment the following line to opt out
# opt_out_usage

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version '2.100.0'

fastlane_require 'cocoapods'
fastlane_require 'struct'
fastlane_require 'xcodeproj'

lane :beforeRelease do

    ensure_git_branch(
        branch: '(release/*|hotfix/*)'
    )

    ensure_git_status_clean

    # ===

    pod_lib_lint(
        allow_warnings: true,
        quick: true
    )

    # === Remember current version number

    versionNumber = get_version_number(
        xcodeproj: 'Pipeline.xcodeproj',
        target: 'macOS-Pipeline'
    )

    puts 'Current VERSION number: ' + versionNumber

    # === Infer new version number

    defaultNewVersion = git_branch.split('/').last

    # === Define new version number

    useInferredNEWVersionNumber = prompt(
        text: 'Proceed with inferred NEW version number (' + defaultNewVersion + ')?',
        boolean: true
    )

    if useInferredNEWVersionNumber

        newVersionNumber = defaultNewVersion

    else

        newVersionNumber = prompt(
            text: 'New VERSION number:'
        )

    end

    # === Apply NEW version number and increment build number

    increment_version_number(
        xcodeproj: 'Pipeline.xcodeproj',
        version_number: newVersionNumber
    )

    increment_build_number(
        xcodeproj: 'Pipeline.xcodeproj'
    )

    # ===

    newBuildNumber = get_build_number(
        xcodeproj: 'Pipeline.xcodeproj'
    )

    commit_version_bump( # it will fail if more than version bump
        xcodeproj: 'Pipeline.xcodeproj',
        message: 'Version Bump to ' + newVersionNumber + ' (' + newBuildNumber + ')'
    )

    # ===

    version_bump_podspec(
        path: './XCEPipeline.podspec',
        version_number: newVersionNumber
    )

    git_commit(
        path: './XCEPipeline.podspec',
        message: 'Version Bump to ' + newVersionNumber + ' in Podspec file'
    )

end # lane :beforeRelease

lane :regenerateProject do

    # === Remember current version and build numbers

    versionNumber = get_version_number(
        xcodeproj: 'Pipeline.xcodeproj',
        target: 'macOS-Pipeline'
    )

    buildNumber = get_build_number(
        xcodeproj: 'Pipeline.xcodeproj'
    )

    # === Remove completely current project file/package

    # default initial location for any command
    # is inside 'Fastlane' folder

    sh 'cd ./.. && rm -r ./Pipeline.xcodeproj'

    # === Regenerate project

    # default initial location for any command
    # is inside 'Fastlane' folder

    sh 'cd ./.. && struct generate && pod install'

    # === Set proper current version and build numbers

    increment_version_number(
        xcodeproj: 'Pipeline.xcodeproj',
        version_number: versionNumber
    )

    increment_build_number(
        xcodeproj: 'Pipeline.xcodeproj',
        build_number: buildNumber
    )

    # === Sort all project entries

    # default initial location for any command
    # is inside 'Fastlane' folder

    sh 'cd ./.. && xcodeproj sort "Pipeline.xcodeproj"'

    # === Add BUILD PHASE script 'SwiftLintPods'

    # remember, we are in ./fastlane/ folder now...
    fullProjFilePath = Dir.pwd + '/../Pipeline.xcodeproj'

    project = Xcodeproj::Project.open(fullProjFilePath)

    project
        .targets
        .select{ |t| ['iOS-Pipeline', 'watchOS-Pipeline', 'tvOS-Pipeline', 'macOS-Pipeline', 'iOS-PipelineTests', 'tvOS-PipelineTests', 'macOS-PipelineTests'].include?(t.name) }
        .each{ |t|

            thePhase = t.new_shell_script_build_phase('SwiftLintPods')
            thePhase.shell_script = '"${PODS_ROOT}/SwiftLint/swiftlint"'
            # thePhase.run_only_for_deployment_postprocessing = '1'

            t.build_phases.delete(thePhase)
            t.build_phases.unshift(thePhase)

        }

    project.save()

end # lane :regenerateProject

lane :generateProject do

    # === Generate project from scratch

    # default initial location for any command
    # is inside 'Fastlane' folder

    sh 'cd ./.. && struct generate && pod update'

    # === Set proper build number

    # NOTE: proper version number is stored in the Info files

    newBuildNumber = prompt(
        text: 'Desired BUILD number:'
    )

    increment_build_number(
        xcodeproj: 'Pipeline.xcodeproj',
        build_number: newBuildNumber
    )

    # === Sort all project entries

    # default initial location for any command
    # is inside 'Fastlane' folder

    sh 'cd ./.. && xcodeproj sort "Pipeline.xcodeproj"'

    # === Add BUILD PHASE script 'SwiftLintPods'

    # remember, we are in ./fastlane/ folder now...
    fullProjFilePath = Dir.pwd + '/../Pipeline.xcodeproj'

    project = Xcodeproj::Project.open(fullProjFilePath)

    project
        .targets
        .select{ |t| ['iOS-Pipeline', 'watchOS-Pipeline', 'tvOS-Pipeline', 'macOS-Pipeline', 'iOS-PipelineTests', 'tvOS-PipelineTests', 'macOS-PipelineTests'].include?(t.name) }
        .each{ |t|

            thePhase = t.new_shell_script_build_phase('SwiftLintPods')
            thePhase.shell_script = '"${PODS_ROOT}/SwiftLint/swiftlint"'
            # thePhase.run_only_for_deployment_postprocessing = '1'

            t.build_phases.delete(thePhase)
            t.build_phases.unshift(thePhase)

        }

    project.save()

end # lane :generateProject